### Obtener todos lo roles
GET http://localhost:3000/api/v1/roles
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTllYWExNy1iNGNjLTc1YWYtYmNhYy02ODQ5MzBkNDg5YTEiLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzgxMjk1NjIxLCJleHAiOjE3ODEyOTkyMjF9.2jaeagNBxHXFOJgyX84n1-g-8YSr3XlVPOQtHVfxSok

### Obtener un rol por su id
GET http://localhost:3000/api/v1/roles/019eaa17-b4a9-70fb-aa09-13979b973231
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTllYWExNy1iNGNjLTc1YWYtYmNhYy02ODQ5MzBkNDg5YTEiLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzgxMjk1NjIxLCJleHAiOjE3ODEyOTkyMjF9.2jaeagNBxHXFOJgyX84n1-g-8YSr3XlVPOQtHVfxSok