### Obtener el catálogo de los tipos de documentos
GET http://localhost:3000/api/v1/document-types
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTllYWExNy1iNGNjLTc1YWYtYmNhYy02ODQ5MzBkNDg5YTEiLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzgxMjc4MTQ5LCJleHAiOjE3ODEyODE3NDl9.1_hJ7JzVE0d5CveilMHtvfBo4ZDsR5vPkS-P0oqi2BM

### Obtner el catálogo de los estados de los documentos
GET http://localhost:3000/api/v1/document-statuses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTllYWExNy1iNGNjLTc1YWYtYmNhYy02ODQ5MzBkNDg5YTEiLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzgxMjc4MTQ5LCJleHAiOjE3ODEyODE3NDl9.1_hJ7JzVE0d5CveilMHtvfBo4ZDsR5vPkS-P0oqi2BM