### Obtener el catálogo de los tipos de documentos
GET http://localhost:3000/api/v1/document-types
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTllYWExNy1iNGNjLTc1YWYtYmNhYy02ODQ5MzBkNDg5YTEiLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzgxMjM3OTI4LCJleHAiOjE3ODEyNDE1Mjh9.c8Okrb3L4dI_8xYrUmcigRk3zHH_F1c3aHMSCa7YXKI

### Obtner el catálogo de los estados de los documentos
GET http://localhost:3000/api/v1/document-statuses
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMTllYWExNy1iNGNjLTc1YWYtYmNhYy02ODQ5MzBkNDg5YTEiLCJ1c2VybmFtZSI6ImFkbWluIiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNzgxMjM3OTI4LCJleHAiOjE3ODEyNDE1Mjh9.c8Okrb3L4dI_8xYrUmcigRk3zHH_F1c3aHMSCa7YXKI